# Generated by Django 3.2.6 on 2021-08-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_project_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='travelapp.svg', upload_to='assets/img'),
        ),
    ]
