# Generated by Django 3.2.6 on 2021-08-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='{% static assets/img/travelapp.svg %}', upload_to='assets/img'),
        ),
    ]
